package fingerprint

import "regexp"

func rule(id string, source Source, key, pattern string, weight int, description string) Rule {
	return Rule{ID: id, Source: source, Key: key, Pattern: pattern, Weight: weight, Description: description,
		Sensitive: source == SourceCookie, Regex: regexp.MustCompile("(?i)" + pattern)}
}

func product(name, category string, rules ...Rule) Fingerprint {
	return Fingerprint{Name: name, Category: category, Rules: rules}
}

// DefaultDatabase returns precompiled built-in HTTP fingerprints.
func DefaultDatabase() []Fingerprint {
	h := SourceHeader
	hv := SourceHeaderValue
	c := SourceCookie
	b := SourceBody
	return []Fingerprint{
		product("Cloudflare", "WAF/CDN", rule("cf-ray", h, "CF-Ray", ".+", 40, "Header CF-Ray detected"), rule("cf-cache", h, "CF-Cache-Status", ".+", 35, "Header CF-Cache-Status detected"), rule("cf-cookie", c, "", `^(?:__cf_bm|cf_clearance)$`, 35, "Cloudflare cookie detected"), rule("cf-server", hv, "Server", `cloudflare`, 30, "Server header contains cloudflare"), rule("cf-body", b, "", `cloudflare ray id|attention required.*cloudflare`, 25, "Cloudflare error page detected")),
		product("Akamai", "WAF/CDN", rule("akamai-grn", h, "Akamai-GRN", ".+", 40, "Header Akamai-GRN detected"), rule("akamai-transform", h, "X-Akamai-Transformed", ".+", 40, "Header X-Akamai-Transformed detected"), rule("akamai-server", hv, "Server", `AkamaiGHost`, 30, "Server identifies AkamaiGHost"), rule("akamai-header", hv, "", `akamai`, 15, "Response header contains Akamai"), rule("akamai-body", b, "", `akamai reference|reference #[0-9a-f.]+`, 25, "Akamai error page detected")),
		product("F5 BIG-IP / ASM / Advanced WAF", "WAF/Reverse Proxy", rule("f5-bigip", c, "", `^BIGipServer`, 40, "BIG-IP persistence cookie detected"), rule("f5-ts", c, "", `^TS[0-9a-f]{6,}`, 30, "F5-style TS cookie detected"), rule("f5-wa", h, "X-WA-Info", ".+", 40, "Header X-WA-Info detected"), rule("f5-body", b, "", `the requested url was rejected|support id:`, 20, "F5-style rejection page detected")),
		product("Imperva / Incapsula", "WAF/CDN", rule("incap-cookie", c, "", `^(?:visid_incap|incap_ses|nlbi_)`, 35, "Imperva cookie detected"), rule("incap-iinfo", h, "X-Iinfo", ".+", 40, "Header X-Iinfo detected"), rule("incap-body", b, "", `incapsula incident id|powered by imperva`, 25, "Imperva block page detected")),
		product("AWS CloudFront / AWS WAF", "WAF/CDN", rule("aws-cf-id", h, "X-Amz-Cf-Id", ".+", 40, "Header X-Amz-Cf-Id detected"), rule("aws-cf-pop", h, "X-Amz-Cf-Pop", ".+", 40, "Header X-Amz-Cf-Pop detected"), rule("aws-via", hv, "Via", `cloudfront`, 30, "Via header contains CloudFront"), rule("aws-cache", hv, "X-Cache", `cloudfront`, 30, "X-Cache contains CloudFront"), rule("aws-body", b, "", `request blocked.*aws|generated by cloudfront`, 25, "AWS block page detected")),
		product("Azure Front Door / Application Gateway", "WAF/CDN", rule("azure-ref", h, "X-Azure-Ref", ".+", 40, "Header X-Azure-Ref detected"), rule("azure-arr", c, "", `^(?:ARRAffinity|ApplicationGatewayAffinity)`, 35, "Azure affinity cookie detected"), rule("azure-body", b, "", `azure front door|application gateway`, 20, "Azure gateway page detected")),
		product("Fastly", "CDN", rule("fastly-served", h, "X-Served-By", ".+", 20, "Header X-Served-By detected"), rule("fastly-hits", h, "X-Cache-Hits", ".+", 20, "Header X-Cache-Hits detected"), rule("fastly-digest", h, "Fastly-Debug-Digest", ".+", 40, "Header Fastly-Debug-Digest detected"), rule("fastly-via", hv, "Via", `fastly|varnish`, 15, "Via header suggests Fastly")),
		product("Sucuri", "WAF/CDN", rule("sucuri-id", h, "X-Sucuri-ID", ".+", 40, "Header X-Sucuri-ID detected"), rule("sucuri-cache", h, "X-Sucuri-Cache", ".+", 35, "Header X-Sucuri-Cache detected"), rule("sucuri-server", hv, "Server", `sucuri|cloudproxy`, 30, "Server identifies Sucuri"), rule("sucuri-body", b, "", `access denied.*sucuri|sucuri website firewall`, 25, "Sucuri block page detected")),
		product("Barracuda WAF", "WAF", rule("barracuda-cookie", c, "", `^(?:barra_counter_session|BNI__)`, 35, "Barracuda cookie detected"), rule("barracuda-body", b, "", `barracuda web application firewall`, 30, "Barracuda block page detected")),
		product("FortiWeb", "WAF", rule("forti-cookie", c, "", `^FORTIWAFSID$`, 40, "FortiWeb cookie detected"), rule("forti-server", hv, "Server", `fortiweb`, 35, "Server identifies FortiWeb"), rule("forti-body", b, "", `fortiweb`, 25, "FortiWeb page detected")),
		product("Citrix NetScaler / ADC", "Reverse Proxy/WAF", rule("citrix-cookie", c, "", `^(?:NSC_|citrix_ns_id)`, 35, "Citrix persistence cookie detected"), rule("citrix-via", hv, "Via", `netscaler|citrix`, 30, "Via identifies Citrix ADC")),
		product("Radware", "WAF", rule("radware-cookie", c, "", `^(?:rdwr|Radware)`, 35, "Radware cookie detected"), rule("radware-body", b, "", `radware|cloudwebsec`, 25, "Radware page detected")),
		product("StackPath", "WAF/CDN", rule("stackpath", hv, "", `stackpath`, 35, "Response header identifies StackPath"), rule("stackpath-sp", h, "X-SP-URL", ".+", 35, "StackPath header detected")),
		product("Varnish", "Reverse Proxy/Cache", rule("varnish-via", hv, "Via", `varnish`, 25, "Via contains Varnish"), rule("varnish", h, "X-Varnish", ".+", 30, "Header X-Varnish detected"), rule("varnish-age", h, "Age", ".+", 5, "Cache Age header detected")),
		product("Nginx", "Web Server/Reverse Proxy", rule("nginx-server", hv, "Server", `nginx`, 30, "Server identifies Nginx"), rule("nginx-body", b, "", `<center>nginx</center>`, 15, "Nginx error page detected")),
		product("HAProxy", "Reverse Proxy", rule("haproxy-server", hv, "Server", `haproxy`, 30, "Server identifies HAProxy"), rule("haproxy-cookie", c, "", `^(?:SERVERID|SRV)`, 15, "Possible HAProxy persistence cookie detected")),
		product("ModSecurity", "WAF", rule("modsec-header", hv, "", `mod_security|modsecurity`, 35, "Header identifies ModSecurity"), rule("modsec-body", b, "", `mod_security|modsecurity|not acceptable.*appropriate representation`, 25, "ModSecurity-style block page detected")),
		product("Generic WAF / Unknown reverse proxy", "WAF/Reverse Proxy", rule("generic-request-id", h, "X-Request-ID", ".+", 5, "Generic request ID header detected"), rule("generic-proxy", hv, "Via", `proxy|gateway`, 10, "Via suggests a proxy"), rule("generic-block", b, "", `request (?:was )?blocked|access denied|web application firewall`, 10, "Generic block page detected")),
	}
}
